export const FETCH_RECIPIENTS_START = 'FETCH_RECIPIENTS_START';
export const FETCH_RECIPIENTS_SUCCESS = 'FETCH_RECIPIENTS_SUCCESS';
export const FETCH_RECIPIENTS_FAILED = 'FETCH_RECIPIENTS_FAILED';
export const CREATE_RECIPIENT_START = 'CREATE_RECIPIENT_START';
export const CREATE_RECIPIENT_SUCCESS = 'CREATE_RECIPIENT_SUCCESS';
export const CREATE_RECIPIENT_FAILED = 'CREATE_RECIPIENT_FAILED';

export const FETCH_INVENTORY_START = 'FETCH_INVENTORY_START';
export const FETCH_INVENTORY_SUCCESS = 'FETCH_INVENTORY_SUCCESS';
export const FETCH_INVENTORY_FAILED = 'FETCH_INVENTORY_FAILED';
export const CREATE_INVENTORY_START = 'CREATE_INVENTORY_START';
export const CREATE_INVENTORY_SUCCESS = 'CREATE_INVENTORY_SUCCESS';
export const CREATE_INVENTORY_FAILED = 'CREATE_INVENTORY_FAILED';

export const FETCH_USERS_START = 'FETCH_USERS_START';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAILED = 'FETCH_USERS_FAILED';
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';
export const ADD_USER_FAILED = 'ADD_USER_FAILED'

export const FETCH_DISCOUNTS_START = 'FETCH_DISCOUNTS_START';
export const FETCH_DISCOUNTS_SUCCESS = 'FETCH_DISCOUNTS_SUCCESS';
export const FETCH_DISCOUNTS_FAILED = 'FETCH_DISCOUNTS_FAILED';

export const FETCH_ORDERS_START = 'FETCH_ORDERS_START';
export const FETCH_ORDERS_AND_UPDATE_SUCCESS = 'FETCH_ORDERS_AND_UPDATE'
export const GET_ORDERS_SUCCESS = 'GET_ORDERS_SUCCESS'

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const GET_SUDO_SUCCESS = 'SUDO_SUCCESS';
export const CHANGE_SUDO_SUCCESS = 'CHANGE_SUDO_SUCCESS'
